var words={
	les1:{
		title:"政治",
		sentences:[
	[{char:"中",level:1},
{char:"华",level:3},
{char:"初",level:1},
{char:"繁",level:2}],
[{char:"睡",level:1},
{char:"狮",level:2},
{char:"渐",level:2},
{char:"醒",level:2}],
[{char:"玖",level:5},
{char:"久",level:1},
{char:"纪",level:1},
{char:"末",level:3}],
[{char:"千",level:1},
{char:"年",level:1},
{char:"始",level:1},
{char:"零",level:1}],
[{char:"宏 ",level:3},
{char:"业",level:1},
{char:"盛",level:3},
{char:"昌 ",level:4}],
[{char:"妙 ",level:2},
{char:"策 ",level:2},
{char:"禀",level:5},
{char:"迎 ",level:1}],
[{char:"左 ",level:1},
{char:"右 ",level:1},
{char:"兼 ",level:3},
{char:"顾",level:1}],
[{char:"总 ",level:1},
{char:"揽 ",level:5},
{char:" 统 ",level:2},
{char:" 领",level:1}],
[{char:"内 ",level:1},
{char:"取  ",level:1},
{char:"稳  ",level:2},
{char:"进 ",level:1}],
[{char:"外 ",level:1},
{char:"交 ",level:1},
{char:" 志 ",level:1},
{char:"同",level:1}],
[{char:"阶 ",level:2},
{char:"梯 ",level:2},
{char:"过 ",level:1},
{char:"度",level:1}],
[{char:"切 ",level:1},
{char:"忌 ",level:4},
{char:"狠 ",level:3},
{char:"猛",level:3}],
[{char:"六 ",level:1},
{char:"贼 ",level:4},
{char:"七 ",level:1},
{char:"害",level:2}],
[{char:"监 ",level:3},
{char:"视 ",level:1},
{char:"审 ",level:3},
{char:"听",level:1}],
[{char:"戒 ",level:4},
{char:"贪 ",level:4},
{char:"须 ",level:1},
{char:"效",level:2}],
[{char:"践 ",level:1},
{char:"约 ",level:2},
{char:"宜 ",level:1},
{char:"恒",level:4}],
[{char:"贬 ",level:5},
{char:"恶 ",level:3},
{char:"褒 ",level:5},
{char:"绩",level:1}],
[{char:"赏 ",level:3},
{char:"劝",level:2},
{char:"罚 ",level:3},
{char:"惩",level:4}],
[{char:"操 ",level:1},
{char:"刃 ",level:4},
{char:"执 ",level:2},
{char:"斧",level:4}],
[{char:"塞 ",level:3},
{char:"涓",level:6},
{char:"救 ",level:2},
{char:"荧",level:5}],
[{char:"势 ",level:2},
{char:"如  ",level:1},
{char:"突 ",level:1},
{char:"起 ",level:1}],
[{char:"抽 ",level:1},
{char:"薪 ",level:4},
{char:"熄 ",level:4},
{char:"平",level:1}],
[{char:"途 ",level:2},
{char:"逢 ",level:2},
{char:"险 ",level:1},
{char:"兆",level:4}],
[{char:"消",level:1},
{char:"芽 ",level:3},
{char:"于 ",level:2},
{char:"萌",level:4}],
[{char:"调 ",level:1},
{char:"息 ",level:1},
{char:"止 ",level:2},
{char:"纷",level:2}],
[{char:"贵 ",level:1},
{char:"在 ",level:1},
{char:"用 ",level:1},
{char:"衡",level:3}],
[{char:"依 ",level:2},
{char:"法 ",level:1},
{char:"谋 ",level:3},
{char:"治",level:1}],
[{char:"官 ",level:2},
{char:"吏 ",level:5},
{char:"皆",level:4},
{char:"正",level:1}]
		]

	}
}